### ISSUE TITLE
Proxy is always the same

### ISSUE THREAD

**Issue by caravan4eg** [rootVIII/proxy_requests#6]
I've noticed that if I 10 times call ProxyRequest I get always the same first proxy from the list. Is it possible to get a random proxy from the list?

**Comment by rootVIII** [comment]
Well, you can't pick the proxy no. BUT you should be creating a new instance of the object with each iteration. Here is an example from my interpreter:

```
>>> for i in range(4):
...     r = ProxyRequests("https://api.ipify.org")
...     r.get() 
...     print(r)
... 
170.0.112.2
77.59.248.61
212.66.38.103
170.0.112.2
>>> 
```
That's the safest way to do it because each instance of the object has so many proxies associated with it. The proxy still **may show up more than once** (there is one that repeats above), but it really depends on whether sslproxies.org has been updated or not... it should get refreshed every 10 mins...

You may also do it like this if you don't use a loop that is too long.

```
>>> r = ProxyRequests("https://api.ipify.org")
>>> for i in range(13):
...     r.get() 
...     print(r)
... 
212.66.38.103
77.59.248.61
177.67.144.94
180.249.227.234
186.193.10.2
202.138.242.36
45.166.84.6
188.95.77.2
180.180.124.248
110.172.160.42
202.60.225.49
212.112.115.253
201.238.191.170
>>> 

```

This is not  the safest way and should be avoided in very long loops... as only 1 instance of the object was created, it will eventually run out of scraped proxy IPs
